---
title: Oxygen project using MIMIC data
author: Willem van den Boom
date: December 31, 2018
output:
  html_document: default
editor_options:
  chunk_output_type: inline
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, results='hide'}
if(!require(bigrquery)) {
  install.packages("bigrquery")
  library("bigrquery")
}

# Project ID from Google Cloud
project_id <- "oxygenators-209612"
options(httr_oauth_cache=FALSE)

# Wrapper for running BigQuery queries.
run_query <- function(query){
    data <- query_exec(query, project=project_id, use_legacy_sql = FALSE, max_pages = Inf)
    return(data)
}

# Library for fitting generalized additive models (GAMs)
library(mgcv)
if(!require(mgcv)) {
  install.packages("mgcv")
  library("mgcv")
}
```



## Analysis

```{r}
library(readr)
pat <- run_query('
SELECT * FROM mimiciii_clinical.final_patients_results
')
```

```{r}
df <- run_query('
SELECT * FROM mimiciii_clinical.measurements_results
')
```

```{r}
summary(as.numeric(table(df$patient_ID)))
df$spO2_Value[df$spO2_Value > 100 | df$spO2_Value < 10] <- NA
pat$age[pat$age > 150] <- NA
pat$mortality <- pat$mortality_in_ICU #| pat$mortality_in_Hosp
pat$diabetes <- pat$diabetes_complicated | pat$diabetes_uncomplicated
pat$tidal_count_percentage[is.na(pat$tidal_count_percentage)] = 0
pat$first_care_unit <- as.factor(pat$first_care_unit)
```

```{r include=FALSE, eval=FALSE}
save.image(file = "RData/MIMIC_data_analysis_v1_checkpoint_1.RData")
```

```{r}
print(summary(df$spO2_Value))
print(summary(pat))
```


```{r}
pat$median <- NA
pat$nOxy <- NA
n <- nrow(pat)
pb <- txtProgressBar(max = n, style = 3)
for(i in 1:n) {
  tmp <- df$spO2_Value[df$patient_ID == pat$patient_ID[i]]
  pat$median[i] <- median(tmp)
  pat$nOxy[i] <- sum(!is.na(tmp))
  setTxtProgressBar(pb, i)
}
close(pb)
summary(pat$median)
summary(pat$nOxy)
```


```{r}
pat$mortality[pat$nOxy < 72] <- NA
```

```{r}
boxplot(pat$median ~ pat$mortality)
```




```{r}
gamfitMed <- gam(mortality ~ s(median)+gender+s(age), data = pat, family = binomial)
summary(gamfitMed)

logistic <- function(x) 1/(1+exp(-x))
xRange = c(92, 100)
yRange = c(0, .35)

xlab <- "Median oxygen saturation (SpO2)"
ylab <- "Probability of ICU mortality" 

xName <- "median"

main <- "Median of measurements"

# Color for dotted line
colD <- "Black"

    plot(1, type = 'n', xlim = xRange, ylim = yRange,
         ylab = ylab,
         xlab = xlab, main = main, yaxs = 'i', xaxs = 'i', yaxt = 'n', xaxt = 'n')
    
    att <- pretty(yRange)
if(!isTRUE(all.equal(att, round(att, digits = 2)))) {
  axis(2, at = att, lab = paste0(sprintf('%.1f', att*100), '%'), las = TRUE)
} else axis(2, at = att, lab = paste0(att*100, '%'), las = TRUE)
    
    att <- pretty(xRange)
    axis(1, at = att, lab = paste0(att, '%'), las = TRUE)

    
    eval(parse(text = paste(c('predictionsPlusCI <- predict(gamfitMed, newdata = data.frame(',
                              xName, ' = gamfitMed$model$', xName, ", gender = 'F', age = median(gamfitMed$model$age)), type = 'link', se.fit = T)"), collapse = "")))

  
  # We have to use the data on which GAM was fit for confidence region as the GAM does not provide standard errors for 'new' input
  eval(parse(text = paste0('xx <- gamfitMed$model$', xName)))
  ord.index <- order(xx)
  xx <- xx[ord.index]
  
  if(gamfitMed$family$link == 'logit') {
    lcl <- logistic(predictionsPlusCI$fit[ord.index] - 1.96*predictionsPlusCI$se.fit[ord.index])
    ucl <- logistic(predictionsPlusCI$fit[ord.index] + 1.96*predictionsPlusCI$se.fit[ord.index])
    
    lines(x = xx, y = lcl, lty = 2, lwd = 2, col = colD)
    lines(x = xx, y = ucl, lty = 2, lwd = 2, col = colD)
    lines(xx, logistic(predictionsPlusCI$fit[ord.index]), lwd = 3)
  } else {
    lcl <- predictionsPlusCI$fit[ord.index] - 1.96*predictionsPlusCI$se.fit[ord.index]
    ucl <- predictionsPlusCI$fit[ord.index] + 1.96*predictionsPlusCI$se.fit[ord.index]
    
    lines(x = xx, y = lcl, lty = 2, lwd = 2)
    lines(x = xx, y = ucl, lty = 2, lwd = 2)
    lines(xx, predictionsPlusCI$fit[ord.index], lwd = 3)
  }




```





Check whether proportion of time in range affects outcome


```{r}
pat$prop <- NA
pb <- txtProgressBar(max = n, style = 3)
for(i in 1:n) {
  id <- pat$patient_ID[i]
  pat$prop[i] <- mean(df$spO2_Value[df$patient_ID == id] >= 94 & df$spO2_Value[df$patient_ID == id] <= 97, na.rm = TRUE)
  setTxtProgressBar(pb,i)
}
close(pb)
summary(pat$prop)
```


```{r include=FALSE, eval=FALSE}
save.image(file = "RData/MIMIC_data_analysis_v1_checkpoint_2.RData")
```


```{r}
boxplot(pat$prop ~ pat$mortality)
```



```{r}
gamfitProp <- gam(mortality ~ s(prop)+gender+s(age), data = pat, family = binomial)
summary(gamfitProp)

logistic <- function(x) 1/(1+exp(-x))
xRange = c(0, max(pat$prop, na.rm= TRUE))
yRange = c(0, .3)

xlab <- "Proportion of time with an SpO2 within 94 to 97"
ylab <- "Probability of ICU mortality" 

xName <- "prop"

main <- "Effect of treatment regime"

    plot(1, type = 'n', xlim = xRange, ylim = yRange,
         ylab = ylab,
         xlab = xlab, main = main, yaxs = 'i', xaxs = 'i', yaxt = 'n', xaxt = 'n')
    
    att <- pretty(yRange)
if(!isTRUE(all.equal(att, round(att, digits = 2)))) {
  axis(2, at = att, lab = paste0(sprintf('%.1f', att*100), '%'), las = TRUE)
} else axis(2, at = att, lab = paste0(att*100, '%'), las = TRUE)
    
    att <- pretty(xRange)
    axis(1, at = att, lab = paste0(att*100, '%'), las = TRUE)

    
    eval(parse(text = paste(c('predictionsPlusCI <- predict(gamfitProp, newdata = data.frame(',
                              xName, ' = gamfitProp$model$', xName, ", gender = 'F', age = median(gamfitProp$model$age)), type = 'link', se.fit = T)"), collapse = "")))

  
  # We have to use the data on which GAM was fit for confidence region as the GAM does not provide standard errors for 'new' input
  eval(parse(text = paste0('xx <- gamfitProp$model$', xName)))
  ord.index <- order(xx)
  xx <- xx[ord.index]
  
  if(gamfitProp$family$link == 'logit') {
    lcl <- logistic(predictionsPlusCI$fit[ord.index] - 1.96*predictionsPlusCI$se.fit[ord.index])
    ucl <- logistic(predictionsPlusCI$fit[ord.index] + 1.96*predictionsPlusCI$se.fit[ord.index])
    
    lines(x = xx, y = lcl, lty = 2, lwd = 2)
    lines(x = xx, y = ucl, lty = 2, lwd = 2)
    lines(xx, logistic(predictionsPlusCI$fit[ord.index]), lwd = 3)
  } else {
    lcl <- predictionsPlusCI$fit[ord.index] - 1.96*predictionsPlusCI$se.fit[ord.index]
    ucl <- predictionsPlusCI$fit[ord.index] + 1.96*predictionsPlusCI$se.fit[ord.index]
    
    lines(x = xx, y = lcl, lty = 2, lwd = 2)
    lines(x = xx, y = ucl, lty = 2, lwd = 2)
    lines(xx, predictionsPlusCI$fit[ord.index], lwd = 3)
  }




```





Extract odds ratios

```{r}
    eval(parse(text = paste(c("predictionsPlusCI <- predict(gamfitMed, newdata = data.frame(median = c(96, 100), gender = 'F', age = median(gamfitMed$model$age)), type = 'link', se.fit = T)"), collapse = "")))

mm <- logistic(predictionsPlusCI$fit)
ll <- logistic(predictionsPlusCI$fit - 1.96*predictionsPlusCI$se.fit)
uu <- logistic(predictionsPlusCI$fit + 1.96*predictionsPlusCI$se.fit)

mm[2]/mm[1]
ll[2]/ll[1]
uu[2]/uu[1]
```

```{r}
    eval(parse(text = paste(c("predictionsPlusCI <- predict(gamfitProp, newdata = data.frame(prop = c(.8, .4), gender = 'F', age = median(gamfitMed$model$age)), type = 'link', se.fit = T)"), collapse = "")))

mm <- logistic(predictionsPlusCI$fit)
ll <- logistic(predictionsPlusCI$fit - 1.96*predictionsPlusCI$se.fit)
uu <- logistic(predictionsPlusCI$fit + 1.96*predictionsPlusCI$se.fit)

mm[2]/mm[1]
ll[2]/ll[1]
uu[2]/uu[1]
```
